# Generated by Django 5.2.8 on 2025-12-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_resumeitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeitem',
            name='category',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
