# Generated by Django 5.2.8 on 2025-12-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_resumeitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeitem',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
