# Generated by Django 5.2.8 on 2025-12-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_resumeitem_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumeitem',
            old_name='date',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
