# Generated by Django 5.2.8 on 2026-01-10 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_rename_date_resumeitem_start_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectImage',
        ),
    ]
