# Generated by Django 5.2.8 on 2026-01-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_projectimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeitem',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumeitem',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
