# Generated by Django 5.2.8 on 2026-01-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_alter_resumeitem_description_alter_resumeitem_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resumeitem',
            options={'ordering': ['category', 'position', 'id']},
        ),
        migrations.AddField(
            model_name='resumeitem',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
